config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :subjects
    resources :groups do
      resources :groupfollowers, only: [:index, :show, :create, :destroy]
      resources :memberships, only: [:index, :show, :create, :destroy]
      resources :groupposts
    end
    resources :questions do
      resources :answers
    end

    resources :points, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :relationships, only: [:create, :destroy]
  resources :posts, only: [:create, :new, :destroy] do
    resources :comments, only:[:create, :new, :destroy]
    resources :likes, only: [:new, :create, :destroy]
  end
  root 'home#index'

  get "/<%= user.user_name %>"=> 'users#show'
  get '/search' => 'users#search'
  get '/groups' => 'groups#index'
  get  '/groups/:id' => 'groups#show'
  get '/groupposts/:id' => 'groupposts#groupposts'

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :users, through: :memberships
  has_many :groupposts
  has_many :memberships
  has_many :groupfollowers

  validates :name, presence: true
  validates :goal, presence: true
  validates :description, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def create
    user = User.find(params[:user_id])
    group = user.groups.build(group_params)

    if group.save
      redirect_to group_path(group)
    else
      flash.now[:notice] = "Your subject was invalid. Try again!"
      render :'groups/new'
      current_user.groups.delete(group)
      @group = Group.new
      render '/groups/new'
    end
  end

  def index
    @groups = Group.all
  end

  def groups
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @grouppost = Grouppost.new
    @groupposts = Grouppost.order(created_at: :desc)
    @membership = Membership.new
    @groupfollower = Groupfollower.new
    @like = Like.new
    @user = User.new
  end

  def group_params
    params.require(:group).permit(:name, :goal, :description, :topics)
  end
end

app/views/groups/_group_posts.html.erb
<div class="posts-area">
    <div class="post-details">
      <% @groupposts.order(created_at: :desc).each do |post| %>
        <div class="post">
          <div class="poster">
            <div class="image-for-poster pull-left"><%=link_to (image_tag post.user.avatar.url(:thumb), class: "img-circle ", size:'50x50'), user_path(post.user) %></div>
            <div class="post-image-n-time">
              <div class="user-name"><%= link_to "#{post.user.first_name} #{post.user.last_name}", user_path(post.user) %></div>
              <div class="time">posted on <%=post.created_at.strftime("%B %d, %Y, %I:%M %p ") %></div>
            </div>
          </div>

          <div class="post-body"><%= post.body %>
            <ul class="count-comments-n-likes">

             <li class="likes">

              </li>

            </ul>

            <div class="comments-form">

            </div><br><!-- Comments form ends here -->

          </div><!-- Post body ends here-->
        </div><!-- post -->
        <%end%>
    </div>

app/views/groups/_groupfollow.html.erb
  <div class='follow-btn'>
      <%= bootstrap_form_for [User, @group, @groupfollower] do |f| %>
        <%= f.submit 'Follow', class: 'btn btn-primary' %>
      <%end%>
  </div>

app/views/groups/_groupfollow_form.html.erb
<%if current_user%>
  <%Groupfollower.following?(current_user, @group) %>
    <%= render 'groups/unfollowgroup'%>
<%end%>
<%if !current_user%>
  <%= render 'groups/groupfollow'%>
<%end%>

app/views/groups/_join.html.erb
<div>
  <div class='join-btn'>
      <%= bootstrap_form_for [User, @group, @membership] do |f| %>
        <%= f.submit 'JOIN', class: 'btn btn-primary' %>
      <%end%>
  </div>
</div>

app/views/groups/_join_form.html.erb
<%if current_user%>
  <% Membership.is_member?(current_user, @group) %>
    <%= render 'groups/unjoin'%>
<%end%>

<%if !current_user %>
    <%= render 'groups/join'%>
<%end%>

app/views/groups/_unfollowgroup.html.erb
<div class="follow">
  <%= button_to 'Following',user_group_groupfollower_path(current_user, @group, Groupfollower.where(user_id: current_user, group_id: @group.id).first), method: :delete %>
</div>

app/views/groups/_unjoin.html.erb
<div class="liked">

  <%= button_to 'Member', user_group_membership_path(current_user, @group, Membership.where(user_id: current_user, group_id: @group).first), method: :delete %>

</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">

      <h1>All groups directory</h1>
      <% @groups.each do |group| %>
        <ul>
          <li><a href="/groups/<%="#{group.id}" %>"><%= "#{group.name}" %></a></li>
          <li><%= group.goal %></li>
          <li><%= group.description %></li>
        </ul>
      <%end%>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 ">
      <%= bootstrap_form_for [current_user, @group] do |f| %>
        <%= f.text_field :name, required: true %>
        <%= f.text_area :goal, required: true %>
        <%= f.text_area :description, required: true %>
        <%= f.text_area :topics%>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
  <div class="row">
    <aside class="col-md-3 text-center left">
      <h3 class="text-center">Group Admin</h3>
      <ul>
       <li class="nav-image"><%=link_to (image_tag  @group.user.image, class: "img-circle nav-image", size:'30x30') %>
       </li>
      </ul>
      <h3>About</h3>
      <p><%=@group.description%></p>
      <h3>Topics </h3>
      <p><%= @group.topics%></p>
    </aside>
    <div class="col-md-8 col-sm-12 col-xs-12">
      <div class="group-wrapper">
        <div class="group-header">
          <h1 class="text-center"><%= @group.name %></h1>
          <p class="text-center"><%= @group.goal%></p>
        </div>
        <div class="row group-stats">
          <div class="stat col-md-2  col-xs-12">
            <div class="followers"><a href ="/groupposts/<%=@group.id %>"> Posts </a></div>
            <div class="count"><%= @group.groupposts.count %></div>
          </div>
          <div class="stat col-md-2   col-xs-12">
            <div class="followers">Members</div>
            <div class="count"><%= @group.users.count %></div>
          </div>

          <div class="stat col-md-2   col-xs-12">
            <div class="followers">Followers</div>
            <div class="count"><%= @group.groupfollowers.count %></div>
          </div>

          <div class="action-btn col-md-3   col-xs-12">
            <div class="followers"><%= render partial: 'groups/join_form', locals: {group: @group}%>
            </div>
          </div>
          <div class="action-btn col-md-3   col-xs-12">
            <div class="followers"><%= render partial: 'groups/groupfollow_form', locals: {group: @group}%>
            </div>
          </div>
        </div>
      </div>
      <%if current_user %>
        <% if Membership.is_member?(current_user, @group)%>
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <%=bootstrap_form_for [current_user, @group, @grouppost], html: {class: "form center-block"} do |f| %>
                <div class="form-group">
                  <%= f.text_area :body, hide_label: true, required: true, placeholder: "paste a link, create a post, post a update, etc", autofocus: "", class: "form-control" %>
                </div>
                <%= f.submit "Post", class: "btn btn-success btn-large" %>
              <%end%>
            </div>
          </div>
        <%end%>
      <%end%>
      <%= render 'groups/group_posts'%>
      </div>
    </div>
 </div>