config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :subjects
    resources :groups do
      resources :groupfollowers, only: [:index, :show, :create, :destroy]
      resources :memberships, only: [:index, :show, :create, :destroy]
      resources :groupposts
    end
    resources :questions do
      resources :answers
    end

    resources :points, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :relationships, only: [:create, :destroy]
  resources :posts, only: [:create, :new, :destroy] do
    resources :comments, only:[:create, :new, :destroy]
    resources :likes, only: [:new, :create, :destroy]
  end
  root 'home#index'

  get "/<%= user.user_name %>"=> 'users#show'
  get '/search' => 'users#search'
  get '/groups' => 'groups#index'
  get  '/groups/:id' => 'groups#show'
  get '/groupposts/:id' => 'groupposts#groupposts'

end

app/models/user.rb
class User < ActiveRecord::Base
  # has_many :followers, foreign_key: :following_user_id
  # has_many :reverse_followers, foreign_key: :followed_user_id, class_name: "Follower",
  #           dependent: :destroy

  # has_many :followed_users, through: :followers, foreign_key: :followed_user_id
  # has_many :following_users, through: :reverse_followers, foreign_key: :following_user_id
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
            class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  belongs_to :category
  has_many :groupposts
  belongs_to :groups
  has_many :groups, through: :memberships
  has_many :memberships
  has_many :subjects
  has_many :questions
  has_many :answers
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :points
  has_many :groups
  validates :first_name ,presence: true
  validates :last_name, presence: true




  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>",
    thumb: "100x100>", thumbnail: "50x50>", tiny: "30x30>" },
    default_url: "user-default_:style.jpeg",
    storage: :s3,
    url: ":s3_domain_url",
    path: "/:class/:attachment/:id_partition/:style/:filename'",
    s3_credentials: "config/secrets.yml"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.name = auth.info.name
       user.first_name= auth.info.first_name
       user.last_name= auth.info.last_name
       user.image = auth.info.image
       user.email = auth.info.email
       user.location = auth.info.location
       user.oauth_token = auth.credentials.token
       user.oauth_expires_at = Time.at(auth.credentials.expires_at)
       user.save!
    end
  end

  def self.users_by_category(query,user,category_id)
    where("category_id = ? AND (first_name LIKE ? OR last_name LIKE ?)", category_id, "%#{query}%", "%#{query}%")
  end

  def self.search_users(query, user)
    where("first_name like ? OR last_name like ?", "%#{query}%", "%#{query}%")
  end

  def self.suggested_users(category)
    user_ids = category.user_ids
    where("id IN (?)", user_ids)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  protected

  def password_required?
    false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @question = Question.new
    @user = User.find(params[:user_id])
    @post = Post.new
    @comment= Comment.new
    @like = Like.new
    @point = Point.new
    @suggested_users = User.suggested_users(current_user.category)
    @suggested_users.delete(current_user)
    @feed_posts = Post.posts_from_users(current_user).limit(10)
  end

  def search
    if params[:category]
       @search_results = User.users_by_category(params[:search], current_user, params[:category][:id])
       render 'search'
    else
      @search_results = User.search_users(params[:search], current_user)
      render 'search'
    end
  end

  def show
    @feed_posts = Post.posts_from_users(current_user).limit(10)
    if current_user
       @user = current_user
    else
      @user = User.find(params[:id])
    end
    @subject = Subject.new
    @post = Post.new
    @comment= Comment.new
    @like = Like.new
    @point = Point.new
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.all
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
end

app/views/users/_comments_form.html.erb
<div class="comments row">
  <%= bootstrap_form_for [post, @comment], html: {class: 'comment-form'} do |f| %>
  <div class="commenting">
    <div class="input-append pull-left col-md-8">
      <%= f.text_area :description, hide_label: true, size: "",required: true, placeholder: "Add a comment here" %>
    </div>
    <div class="button pull-left">
      <%= f.submit "Comment", class: "comment_button btn btn-default btn-large", size: '10x10' %>
    </div>
  </div>
  <%end%>
</div>

app/views/users/_follow.html.erb
<div class="followers">
  <%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
    <div><%= f.hidden_field :followed_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/users/_follow_form.html.erb
<div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'users/unfollow' %>
    <% else %>
      <%= render 'users/follow' %>
    <% end %>
</div>

app/views/users/_group_posts.html.erb
 <div class="group-post-area">
    <div class="posts-area">
      <div class="post-details">
        <% @groupposts.order(created_at: :desc).each do |post| %>
          <div class="post">
            <div class="poster">
              <div class="image-for-poster pull-left"><%=link_to (image_tag post.user.avatar.url(:thumb), class: "img-circle ", size:'50x50'), user_path(post.user) %></div>
              <div class="post-image-n-time">
                <div class="user-name"><%= link_to "#{post.user.first_name} #{post.user.last_name}", user_path(post.user) %></div>
                <div class="time">posted on <%=post.created_at.strftime("%B %d, %Y, %I:%M %p ") %></div>
              </div>
            </div>

            <div class="post-body"><%= post.body %>
              <div class="comments-form">

              </div><br><!-- Comments form ends here -->

            </div><!-- Post body ends here-->
          </div><!-- post -->
          <%end%>
        </div>
    </div>
  </div>

app/views/users/_suggested_users.html.erb
  <div class= "row">
    <%User.order(created_at: :desc).limit(10).each do |user| %>

      <%if !current_user.following?(user)%>

        <div class="basic_info span4">
          <ul class="">
            <div class="text">
              <%= image_tag user.image, :class => "img-circle text-center"%>
            </div>
            <li><a class="user-name" href="/users/<%=user.id%>"><%= user.first_name %> <%=user.last_name %></a></li>
            <li class=""></li>

            <li><%= user.location%></li>

              <div class="followers">
                <%= form_for(current_user.relationships.build(followed_id: user.id)) do |f| %>
                <%= f.hidden_field :followed_id %>
                <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
                <%end%>
              </div>

          </ul>
        </div>
      <%end%>
    <%end%>
  </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete } ) do |f| %>
  <%= f.submit "Following", class: "btn btn-success" %>
<% end %>

app/views/users/_user_home.html.erb
e<div class="row">
  <div class="posts-area">
    <div class="post-details">
      <% current_user.posts.order(created_at: :desc).each do |post| %>
      <div class="poster">
        <div class="image-for-poster pull-left"><%= image_tag current_user.avatar.url(:thumbnail), class: "img-circle post-avatar"%></div>
        <div class="post-image-n-time">
          <div class="user-name"><a> <%= current_user.first_name %> <%= current_user.last_name %></a></div>
          <div class="time">posted on <%=post.created_at.strftime("%B %d, %Y, %I:%M %p ") %></div>
        </div>
      </div>
        <div class="post-body"><%= post.body %>
            <ul class="count-comments-n-likes">
            <li><%= render partial: 'users/like_form', locals: {post: post}%></li>
             <li class="likes">
                <span class='likes-count'><%= (post.comments.count) || post.comments.count = 0 %></span> Comments
              </li>
              <li class="comments"><%= (post.likes.count) || post.likes.count = 0 %> likes</li>
            </ul>

            <div class="comments-form">
              <%= render partial: 'users/comments_form', locals: {post: post} %>
            </div><br><!-- Comments form ends here -->
            <%if post.comments.any?%>
              <div class="comments-details row">
                <ul id="comment-for-post">
                  <% post.comments.each do |comment| %>
                    <li>
                      <aside class="commenter-image pull-left">
                        <%=link_to (image_tag post.user.avatar.url(:thumb), class: "img-circle ", size:'40x40'), user_path(current_user) %>
                      </aside>
                        <%=link_to "#{comment.user.first_name} #{comment.user.last_name}", user_path(@user) %>
                        <div class="time">posted on <%=post.created_at.strftime("%B %d, %Y, %I:%M %p ") %></div>
                        <div class="description"><%=comment.description%></div>
                    </li>
                  <%end%>
                </ul>
              </div>
            <%end%>
          </div><!-- Post body ends here-->
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/users/_user_nav.html.erb
<ul class="nav nav-tabs" role="tablist" id="myTab">
  <li class="active"><a href="#trends" role="tab" data-toggle="tab">Feed</a></li>
  <li class="home"><a href="#home" role="tab" data-toggle="tab">Home</a></li>
  <li class="questions"><a href="#questions" role="tab" data-toggle="tab">Trending</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active" id="trends">
  <%= render 'users/trends'%>
  </div>
  <div class="tab-pane fade" id="home">
    <%= render 'users/user_posts'  %>
  </div>
</div>

app/views/users/index.html.erb
<div class="wrapper">
  <div class="content">
    <aside class="aside pull-right">
        <ul>
          <li><a class="btn btn-success btn-lg" data-toggle="modal" data-target="#postModal"> + Make New Post</a>
            <%= render 'users/post_form' %>
          </li>
        </ul>
      </aside>
    <div class="row">
      <div class="dashboard">
        <div class="user-info">
          <div class="row text-center stats">
            <div class="user-av span2 pull-left">
              <div class="useravatar"><%= image_tag current_user.avatar.url(:thumb), :class => "img-circle"%></div>
              <ul class="text-center">
                <li text-center><a class="user-name" href="/users"><%= current_user.first_name %> <%=current_user.last_name %></a></li>
                <li class="text-center"><%= current_user.location%></li>
              </ul>
            </div>

            <div class="">
              <%=render 'users/stats'%>
            </div>
          </div>

          <div class="row action-buttons text-center">
            <ul>

              <li class="btn">Credit</li>
              <li class="btn">Full Profile</li>
            </ul>
          </div>
        </div><!--end of user information div -->
      </div><!-- dashboard-->
    </div>

    <ul class="nav nav-tabs" role="tablist" id="myTab">
      <li class="active"><a href="#trends" role="tab" data-toggle="tab">Feed</a></li>
      <li class="home"><a href="#home" role="tab" data-toggle="tab">Home</a></li>
      <li class="membes"><a href="#members" role="tab" data-toggle="tab">Like minded People</a></li>
      <li class="questions"><a href="#questions" role="tab" data-toggle="tab"> Trending </a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane fade in active" id="trends">

      </div>
      <div class="tab-pane fade" id="home">
        <%= render 'users/user_posts'  %>
      </div>
       <div class="tab-pane fade" id="members">
        <%= render 'users/members'  %>
      </div>

    </div><!-- Tab content ends here-->
  </div>
</div>

app/views/users/search.html.erb
<div class="search">

  <div class="row">
    <div class="cat">
    <%= form_tag('/search', method: "get", id: "search-form", class: "navbar-form navbar-bar form-inline", role: "search") do %>
      <%= collection_select :category, :id, Category.all, :id, :name , class: "input-group-addon selection"%>
        <%= text_field_tag :search, params[:search], placeholder: "search users", class: " form-control serch-query  inputsearch"%>
        <%= submit_tag "search", class: "btn btn-default", name: nil %>
      </div>
    <%end%>
  </div>
</div>
<hr>

<div id="search-results" class="search-results">
  <div class="container">
    <h2 class="text-center"><%= @search_results.count %> results found: </h2>
    <div class="most-recent row">
      <% @search_results.each do |user| %>
      <div class="col-md-3 col-sm-3">
        <div class="pull-left user-info">
          <div class="useravatar text-center"><%=link_to (image_tag user.avatar.url(:thumb), class: "img-circle ", size:'40x40'), user_path(user) %></div>
          <ul>
            <li class="user-name"><%=link_to "#{user.first_name} #{user.last_name}", user_path(user) %></li>
            <%if params[:category ] %>
              <%= user.category.name %>
            <%end%>
            <li><%= user.location%>
            <li>
                <% if current_user.following?(user) %>
                  <div class= "following">
                    <%= link_to 'Following', user_path(user), class: 'btn btn-success'%>
                  </div>

                <% else %>
                  <div class="followers">
                    <%= form_for(current_user.relationships.build(followed_id: user.id)) do |f| %>
                    <%= f.hidden_field :followed_id %>
                    <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
                  </div>
                  <%end%>
              <%end%>
            </li>
          </ul>
        </div>

      </div>
       <%end%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <aside class="aside pull-right">
    <ul>
    <%if current_user == @user %>
      <h3><%= link_to '+', new_user_subject_path(current_user)%>Learning</h3>
      <ul>
        <%current_user.subjects.each do |subject|%>
        <li><%=subject.name%></li>
        <%end%>
      </ul>
    <%else%>
      <h3><%= link_to "Learning", new_user_subject_path(@user)%></h3>
      <ul>
        <%@user.subjects.each do |subject|%>
        <li><%=subject.name%></li>
        <%end%>
      </ul>
    <%end%>

  </aside>
  <div class="row">
    <div class="dashboard pull-left">
        <div class="user-info">
          <div class="row text-center stats">
            <div class="user-av col-md-4 pull-left">
              <div class="useravatar"><%=link_to (image_tag @user.avatar.url(:thumbnail),class: "img-circle"), user_path(current_user) %></div>
              <ul>
                <li class="user-name"><%=link_to "#{current_user.first_name} #{current_user.last_name}", user_path(current_user) %></li>

                <li><%= @user.location %></li>
              </ul>
            </div>
            <div class="col-md-8 col-sm-6 col-xs-5 stats-bar">
              <%= render "users/stats"%>
            </div>
             <div class="user-blurb">
              <i><p class="text-center blurb"></p></i>
            </div>
          </div>

          <div class="row action-buttons text-center">
            <ul class="col-md-12 col-sm-12 col-xs-12">
              <%if current_user != @user %>
                  <li class="btn"><%= render 'users/follow_form'%></li>
                  <li class="btn"><%= render 'users/credit'%></li>
              <%else%>
                 <li><%= link_to 'Update Profile',edit_user_registration_path, class: "btn btn-success" %></li>
                 <li><a class="btn btn-success " data-toggle="modal" data-target="#postModal"> +New Post</a>
                  <%= render 'users/post_form' %>
                </li>
                <li><%=link_to 'Find People', search_path, class: "btn btn-success"%></li>
              <%end%>
            </ul>

          </div>
        </div><!--end of user information div -->
    </div>
  </div><!-- row ends here-->

  <%if current_user == @user%>
    <%= render 'users/user_nav'%>
  <%else%>
    <ul class="nav nav-tabs" role="tablist" id="myTab">
      <li class="active"><a href="#home" role="tab" data-toggle="tab">Posts</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade in active" id="home">
        <%= render 'users/user_posts'  %>
      </div>
    </div>
  <%end%>

  <!-- posts area-->
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
    <h3><%= @title %></h3>
    <% if @users.any? %>

      <% @users.each do |user| %>
        <div class="col-md-5">
         <%= user.first_name%><%= user.last_name%>
        </div>
        <div class="col-md-4">
          <%= render 'users/follow_form' %><br/>
        </div>
       <% end %>

    <%end%>
    </div>
  </div>
</div>